/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_aliases.h"
#include "LED.h"
#include "TECLADO_OUT_aliases.h"
#include "TECLADO_OUT.h"
#include "up.h"
#include "Led_1_aliases.h"
#include "Led_1.h"
#include "Clock_1.h"
#include "teclado.h"
#include "TECLADO_IN_aliases.h"
#include "TECLADO_IN.h"
#include "detectorFaseM1_aliases.h"
#include "detectorFaseM1.h"
#include "faseM1.h"
#include "sentidodegiroM1_aliases.h"
#include "sentidodegiroM1.h"
#include "Clock_2.h"
#include "Motor2_aliases.h"
#include "Motor2.h"
#include "Motor1_aliases.h"
#include "Motor1.h"
#include "M1_aliases.h"
#include "M1.h"
#include "Clock_3.h"
#include "PWM1.h"
#include "Clock_4.h"
#include "PWM2.h"
#include "M2_aliases.h"
#include "M2.h"
#include "detectorFaseM2_aliases.h"
#include "detectorFaseM2.h"
#include "faseM2.h"
#include "sentidodegiroM2_aliases.h"
#include "sentidodegiroM2.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

